expense/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('track.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

track/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.views import logout_then_login

app_name="track"
urlpatterns=[
	# URL for  signup page
    path('signup/',views.signup,name="signup"), 
    # URL for Adding items
    path('item/',views.add_item,name="items"),  
    # URL for displaying
    path('display/',views.display,name="display"),
    # URL for deleting
    path('<int:id>/', views.delete, name='delete'),
    # URL for sorting by name page
    path('sortname/',views.sortbyname,name="sname"), 
    # URL for sorting by price page
    path('sortprice/',views.sortbyprice,name="sprice"),
    # URL for sorting by date page
    path('sortdate/',views.sortbydate,name="sdate"),
    # URL for editing page
    path('<int:id>/edit/',views.update,name="update"),
    # URL for Login
    path('accounts/', include('django.contrib.auth.urls'),name="login"),
   	# URL for Logout
 	path('accounts/logout', include('django.contrib.auth.urls'), name="logout"),
]
 

track/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class NewItem(models.Model):
	#newitem name
	name = models.CharField(max_length = 200, null = True)
	#item price
	price = models.IntegerField(null = True)
	#item image field
	image = models.FileField(blank = True, null = True)
	#Created_time
	created_at = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return self.name

track/forms.py
from django import forms
from django import forms
from . models import NewItem
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

#ThisForm is for the item addition
class NewItemModelForm(forms.ModelForm):
	class Meta:
		model = NewItem
		fields = ('name', 'price', 'image')

#ThisForm is for the User Registration
class SignUpForm(UserCreationForm):
		email = forms.EmailField(max_length = 254, help_text = 'Enter a valid Email address.')
		password1 = forms.CharField(widget = forms.PasswordInput, help_text = 'MIN 8 chars,should include special char,alpha-numeric char')

		class Meta:
			model = User
			fields = ('username', 'email', 'password1', 'password2')	

track/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect,reverse
from django.http import HttpResponse,HttpResponseRedirect
from .forms import NewItemModelForm
from . models import NewItem
from django.db.models import Sum
from django.contrib.auth import authenticate,login
from .forms import SignUpForm
import re,json

# Create your views here.
#View for signing up using custom inbuilt UserCreationForm
def signup(request):        
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        #Checking for form validation and retriving username,pass from POST data
        if form.is_valid():                
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            #User is logged in
            login(request, user)          
            return HttpResponseRedirect('/item')
    else:
        form = SignUpForm()               #IF not logged in then Show empty form
    return render(request, 'registration/signup.html', {'form': form})

def add_item(request):                      # Add all expenses items
    k=NewItem.objects.aggregate(Sum('price'))   # gets total sum of expenses
    l=json.dumps(k)                          # converts into json string
    p=re.findall("\d+",l)                    #Retrives numerical part from returned string
    item = NewItem.objects.all()
    if request.method == "POST":
        form = NewItemModelForm(request.POST,request.FILES)  #request.FILES contains uploaded files
        if form.is_valid():
            # commit=False means the form doesn't save at this time.
            # commit defaults to True which means it normally saves.
            model_instance = form.save(commit=False)
            model_instance.save()
            form = NewItemModelForm()
            return HttpResponseRedirect('/item') #redirects to same page after POST
    else:
        form = NewItemModelForm()
    return render(request, "track/index.html", {'form': form ,'item':item,'sum':p })

#displaying all items
def display(request):                                     
    k = NewItem.objects.aggregate(Sum('price'))
    l = json.dumps(k)
    p = re.findall("\d+", l)
    item = NewItem.objects.all()
    return render(request,"track/table.html",{'items':item ,'sum':p})

# Editing submitted data
def update(request,id):                       
    instance = get_object_or_404(NewItem,id=id)
    form = NewItemModelForm(data=request.POST, files=request.FILES, instance=instance) #posted files will be in request.FILES
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
    context={
        "name":instance.name,
        "price":instance.price,
        "instance":instance,
        "form":form,
    }
    return render(request,"track/update.html",context)

#deleting items by primary key on click    
def delete(request,id):                                    
    deleteitem=get_object_or_404(NewItem,pk=id).delete()
    return HttpResponseRedirect('/display')

#sorting by name
def sortbyname(request):                                  
    sname=NewItem.objects.order_by('name').all()
    return render(request,"track/sname.html",{'name':sname})

#sorting by price    
def sortbyprice(request):                                 
    sprice=NewItem.objects.order_by('price').all()
    return render(request,"track/sprice.html",{'price':sprice})

#sorting by date
def sortbydate(request):                                    
    sdate=NewItem.objects.order_by('created_at').all()
    return render(request,"track/sdate.html",{'date':sdate})

track/templates/track/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'track/style.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Philosopher" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Neuton" rel="stylesheet">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>

    </style>
</head>
<body>
<div class="container-fluid" id="index">
<center>
<!--  Authentication -->
<h1>Welcome to Expenses tracker</h1>
{% if user.is_authenticated %}
    <h2>you have now been logged in as<h1><u>{{user.username}}</u></h1> <h2> Welcome!!</h2></h2>
    <div style="position: absolute; top: 10px; right: 50px; text-align:right;">
    <p><a href="{% url 'logout' %}">Logout</a></p>
  </div>
{% else %}
<h2>you didn't log in </h2>
{% endif %}
<!--   end of authentication -->

<hr>
<!--  Form for adding elements -->
<div class="container" id="login">
<form method="POST" action=" " enctype="multipart/form-data" >
<h1>Add Item</h1>
{% csrf_token %}
{{form.as_p}}
<button class="button button1" type="submit">Add Item</button>
</form>
<form action="{% url 'track:display'%}">
    <button class="button button2" type="submit">Display</button>
</form>
</div>
<!--  end of form -->	

<!--  All filters --->
<hr>
<h2>Filters</h2>
 <form action="{% url 'track:sname'%}">
    <button class="button button5">Sort by name</button>
</form>
<form action="{% url 'track:sprice'%}">
    <button class="button button5">Sort by price</button>
</form>
<form action="{% url 'track:sdate'%}">
    <button class="button button5">Sort by date</button>
</form>
</center>
<!--  End of filter buttons -->
</div>
</body>
</html>

track/templates/track/sdate.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'track/style.css' %}" />
<!-- style sheets are linked above-->

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Sort by Date</title>
</head>
<body>



<!-- table with elements in a loop --->
<table>
    <th>Sno</th>
    <th>Name</th>
    <th>Price</th>
    <th>Created at</th>
    <th>Image</th>
    {% for i in date %}
    <tr>
        <td>{{forloop.counter}}</td>
        <td>{{i.name}}</td>
        <td>{{i.price}}</td>
        <td>{{i.created_at}}</td>
        <td>{% if i.image %}
            <img src="{{i.image.url}}" width="100px" height="100px"/>
            {% endif %}
        <br>
    <form action="{% url 'track:delete' i.id%}">
    <input type="submit" value="Delete Task" id="delete{{forloop.counter}}"/>
    <br>
    </form>
    <form action="{% url 'track:update' i.id%}">
    <input type="submit" value="Edit" id="edit{{forloop.counter}}" />
    </form></td>
    </tr>
    {% endfor %}
</table>
<!-- end of table-->



<br><br><br>
 <form action="{% url 'track:items'%}">
    <button class="button button5">Homepage</button>
</form>
</body>
</html>

track/templates/track/sname.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'track/style.css' %}" />s
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Sort by name</title>
</head>
<body>


<!-- table with elements in a loop --->
<table>
    <th>Sno</th>
    <th>Name</th>
    <th>Price</th>
    <th>Created at</th>
    <th>Image</th>
    {% for i in name %}
    <tr>
        <td>{{forloop.counter}}</td>
        <td>{{i.name}}</td>
        <td>{{i.price}}</td>
        <td>{{i.created_at}}</td>
        <td>{% if i.image %}
            <img src="{{i.image.url}}" width="100px" height="100px"/>
            {% endif %}
        <br>
    <form action="{% url 'track:delete' i.id%}">
    <input type="submit" value="Delete Task" id="delete{{forloop.counter}}"/>
    <br>
    </form>
    <form action="{% url 'track:update' i.id%}">
    <input type="submit" value="Edit" id="edit{{forloop.counter}}"/>
    </form></td>
    </tr>
    {% endfor %}
</table>
<!-- table with elements in a loop --->




<br><br><br>
<form action="{% url 'track:items'%}">
    <button class="button button5">Homepage</button>
</form>
</body>
</html>

track/templates/track/sprice.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'track/style.css' %}" />
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Sort by price</title>
</head>
<body>

<!-- table with elements in a loop --->
<table>
    <th>SL.NO</th>
    <th>Name</th>
    <th>Price</th>
    <th>Created at</th>
    <th>Image</th>
    {% for i in price %}
    <tr>
        <td>{{forloop.counter}}</td>
        <td>{{i.name}}</td>
        <td>{{i.price}}</td>
        <td>{{i.created_at}}</td>
        <td>{% if i.image %}
            <img src="{{i.image.url}}" width="100px" height="100px"/>
            {% endif %}
        <br>
    <form action="{% url 'track:delete' i.id%}">
    <input type="submit" value="Delete Task" id="delete{{forloop.counter}}"/>
    <br>
    </form>
    <form action="{% url 'track:update' i.id%}">
    <input type="submit" value="Edit" id="edit{{forloop.counter}}"/>
    </form></td>
    </tr>
    {% endfor %}
</table>
<!-- table with elements in a loop --->
<br><br><br>
<form action="{% url 'track:items'%}">
    <button class="button button5">Homepage</button>
</form>
</body>
</html>

track/templates/track/table.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'track/style.css' %}" />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<!-- table with elements in a loop --->
<table>
    <th>SL.NO</th>
    <th>Name</th>
    <th>Price</th>
    <th>Created at</th>
    <th>Image</th>
    {% for i in items %}
    <tr>
        <td>{{forloop.counter}}</td>
        <td>{{i.name}}</td>
        <td>{{i.price}}</td>
        <td>{{i.created_at}}</td>
        <td>
            {% if i.image %}
            <img src="{{i.image.url}}" width="100px" height="100px"/>
            {%endif%}
        <br>
    <form action="{% url 'track:delete' i.id%}">
    <input type="submit" value="Delete Task" id="delete{{forloop.counter}}"/>
    <br>
    </form>
    <form action="{% url 'track:update' i.id%}">
    <input type="submit" value="Edit" id="edit{{forloop.counter}}" />
    </form></td>
    </tr>
    {% endfor %}
</table>
<!-- table with elements in a loop --->
<p>The total sum is {{sum}}</p>

<!-- All filters --->
<form action="{% url 'track:items'%}">
    <button type="submit" class="button button1" >Add Items</button>
</form>
<form action="{% url 'track:sprice'%}">
    <button class="button button5">Sort by price</button>
</form>
 <form action="{% url 'track:sname'%}">
    <button class="button button5">Sort by name</button>
</form>
 <form action="{% url 'track:sdate'%}">
     <button class="button button5">Sort by Date</button>
 </form>
<!-- end filters --->
</body>
</html>

track/templates/track/update.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'track/style.css' %}" />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
</head>
<body>

<!-- Form for updating the items --->
<div class="container" id="signup" >
<form method="POST" action="" enctype="multipart/form-data" >
    <h2>Update Item</h2>
{% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}

      </p>
    {% endfor %}
    <button class="button button1" type="submit">Update</button>
</form>
    <!-- end of form --->

 <form action="{% url 'track:display'%}">
    <button class="button button2" type="submit">Display</button>
</form>
</div>
</body>
</html>